config/routes.rb
AtndGrouping::Application.routes.draw do
  resources :groupings, :only => [:new, :show, :create] do
    collection do
      post :preview
    end
  end
  root :to => 'groupings#new'
end

app/models/group.rb
class Group
  include Mongoid::Document
  field :position, :type => Integer
  embedded_in :grouping
  embeds_many :users
end

app/models/grouping.rb
# -*- coding: utf-8 -*-
class Grouping
  include Mongoid::Document
  
  field :event_id, :type => Integer         # event_id  イベントID  757
  field :title, :type => String             # title タイトル  Tokyo Cloud Developers Meetup #02
  field :catch, :type => String             # catch キャッチ  今回のテーマは Google App Engine。
  field :description, :type => String       # description 概要  クラウド・コンピューティングを扱うディベロッパ・エンジニアのカジュアルなイベント Tokyo Cloud の第２回目を開催します。
  field :event_url, :type => String         # event_url ATNDのURL  http://atnd.org/events/757
  field :started_at, :type => DateTime      # started_at  イベント開催日時  2009-06-10T19:00:00+09:00
  field :ended_at, :type => DateTime        # ended_at  イベント終了日時  2009-06-10T21:00:00+09:00
  field :url, :type => String               # url 参考URL http://groups.google.com/group/tokyocloud
  field :limit, :type => Integer            # limit 定員  80
  field :address, :type => String           # address 開催場所  東京都中央区銀座7-2-6
  field :place, :type => String             # place 開催会場  Recruit Annex 1　（リクルートアネックス1）　B1F
  field :lat, :type => Integer              # lat 開催会場の緯度 35.6708529
  field :lon, :type => Integer              # lon 開催会場の経度 139.7605287
  field :accepted, :type => Integer         # accepted  参加者 80
  field :waiting, :type => Integer          # waiting 補欠者 15
  field :updated_at, :type => DateTime      # updated_at  更新日時  2009-06-04T11:56:20Z
  field :owner_id, :type => Integer         # owner_id  主催者のID  132
  field :owner_nickname, :type => String    # owner_nickname  主催者のニックネーム  kawanet
  field :owner_twitter_id, :type => Integer # owner_twitter_id  主催者のtwitter ID  kawanet
  field :owner_id, :type => Integer         # owner_id  主催者のID  132
  
  field :groupings_count, :type => Integer
  
  embeds_many :groups
  embeds_many :users
  
  after_initialize :set_event_id
  
  def pull_atnd_event
    pull_atnd_event_detail(self.event_id)
    pull_atnd_event_users(self.event_id)
  rescue => e
    self.errors.add(:event_id, ': イベントIDに間違えがあります。')
  end
  
  # usersをシャッフルしてgroupsを返す
  def shuffle
    count = self.groupings_count
    groups = []
    users = self.users.dup.shuffle
    people_count = (users.size / count)
    
    count.times do
      group = Group.new
      people_count.times do
        group.users << users.pop
      end
      groups << group
    end
    
    # 余った人の処理
    # FIXME 今は余った人を適当なグループに突っ込むだけ
    unless users.empty?
      users.each do |user|
        group = groups.sample
        group.users << user
      end
    end
    
    self.groups = groups
  end
  
  private
    
    def set_event_id
      if self.event_url.present? && self.event_id.blank? && self.event_url.match(%r{http://atnd.org/events/([0-9]+)})
        self.event_id = $1.to_i
      end
    end
  
    def pull_atnd_event_users(event_id)
      res = HTTParty.get("http://api.atnd.org/events/users/?event_id=#{event_id}&format=json")
      if res.code == 200
        parsed_response = res.parsed_response.with_indifferent_access
        event = parsed_response[:events].first
        users = event[:users]
        self.users = []
        users.each do |user|
          if user[:status] == 1
            u = User.new(user)
            self.users << u
          end
        end
      end
    end
    
    def pull_atnd_event_detail(event_id)
      res = HTTParty.get("http://api.atnd.org/events/?event_id=#{event_id}&format=json")
      if res.code == 200
        parsed_response = res.parsed_response.with_indifferent_access
        event = parsed_response[:events].first
        self.attributes = event
      end
    end
  
end

app/models/user.rb
class User
  include Mongoid::Document
  embedded_in :grouping
  field :user_id, :type => Integer
  field :nickname, :type => String
  field :twitter_id, :type => String
  field :twitter_img, :type => String
  field :status, :type => Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groupings_controller.rb
class GroupingsController < ApplicationController
  respond_to :html, :json
  def new
    @grouping = Grouping.new
    @grouping.event_id = params[:event_id].present? ? params[:event_id] : ''
    @grouping.groupings_count = params[:groupings_count].present? ? params[:groupings_count] : nil
  end
  
  def preview
    @grouping = Grouping.new(params[:grouping])
    if @grouping.valid?
      @grouping.pull_atnd_event
      @grouping.shuffle
      @json = @grouping.to_json({
        :except => [:_id],
        :include => {
          :groups => { 
            :except => [:_id], 
            :include => {
              :users => {
                :except => [:_id]
              },
            },
          },
          :users => { :except => [:_id]},
        }
      })
      respond_with do |format|
        format.html do
          if request.xhr?
            render :partial => 'groupings', :layout => false
          end
        end
      end
    end
  end
  
  def create
    @grouping = Grouping.new params[:grouping]
    if @grouping.save
      render :json => @grouping
    end
  end
  
  def show
    @grouping = Grouping.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def mobile?
    request.user_agent =~ /(Android|iPhone|iPod)/
  end
end

app/helpers/groupings_helper.rb
module GroupingsHelper
end

app/views/groupings/_groupings.html.haml
-if @grouping.errors.any?
  #error_explanation
    %h2= "#{pluralize(@grouping.errors.count, "error")} prohibited this keyword from being saved:"
    %ul
      - @grouping.errors.full_messages.each do |msg|
        %li= msg
- else
  %section.event
    .main
      %h1
        = @grouping.title
        %span.atnd_url= link_to "ATND", @grouping.event_url
      %h2= @grouping.catch
      %ul
        %li= @grouping.started_at.strftime("%Y/%m/%d %H:%M")
        %li= @grouping.address
        %li.owner
          -unless @grouping.owner_twitter_id?
            開催者
            = @grouping.owner_nickname 
    .sub
      -if @grouping.owner_twitter_id?
        %p.owner
          %span
            開催者
            = link_to "http://twitter.com/#{@grouping.owner_twitter_id}", :target => "_blank" do
              %img{:alt => "#{@grouping.owner_twitter_id}", :src => "http://img.tweetimag.es/i/#{@grouping.owner_twitter_id}_n"}
              = @grouping.owner_twitter_id
    
  %p.acceoted_users
    イベントの人数
    %span.number= @grouping.users.size
    人 / 
    グループの数
    %span.number= @grouping.groupings_count

  #groupings
    - num = 0
    - @grouping.groups.each do |group|
      .grouping
        - num += 1
        %h2 Group #{num}
        %ul.users
          - group.users.each do |user|
            %li.user
              %p.icon
                - if user.twitter_img.present? && user.twitter_img != 'null'
                  = image_tag user.twitter_img
                - else
                  = image_tag 'no_icon.gif'
                
              %p.name= truncate user.nickname, :length => 15
  
  %script#results-json(type='text/json')
    = raw @json

  - case action_name
  - when 'preview'
    .next
      %ul
        %li.shuffle= link_to 'やり直す', ''
        %li.result= link_to '確定', ''
  - when 'show'
    .tweet
      %a.twitter-share-button{"data-count" => "vertical", "data-lang" => "ja", :href => "https://twitter.com/share"} ツイート
    %script{:src => "//platform.twitter.com/widgets.js", :type => "text/javascript"}
    .retry
      = link_to '新しくシャッフルする', root_path(:event_id => @grouping.event_id, :groupings_count => @grouping.groupings_count)

app/views/groupings/new.html.haml
%h1.description ATNDイベント参加者をランダムにグループ別け
= form_for @grouping, :url => preview_groupings_path, :remote => true do |f|
  #form
    %fieldset
      %ol
        %li.url
          %p.inner
            %span.label
              = f.label :event_id, 'URL'
              %span.atend_url
                http://atnd.org/events/
            %span.input
              = f.text_field :event_id
          %p.help-block
            ATNDイベントIDを入力 （例：22605 ※半角数字）
        %li.groups
          %p.inner
            %span.label
              = f.label :groupings_count, 'Groups'
            %span.input
              = f.select :groupings_count, options_for_select((2..100).to_a, @grouping.groupings_count), :include_blank => 'グループ数を選択'
      %p.commit
        = f.submit 'シャッフル', :id => 'btn_shuffle'

#results

#loading
  %span シャッフル中

:javascript
   $(function(){
     Grouping.init()
   });

app/views/groupings/show.html.haml
= render :partial => 'groupings'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ATND GROUPING
    = stylesheet_link_tag    "application"
    = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"
    = javascript_include_tag "application"
    = javascript_include_tag "facebox.js"
    %meta(name="viewport" content="width=device-width, height=device-height, initial-scale=1.0")
    %link(rel="icon" type="image/png" href="/favicon.png")
    %link(rel="shortcut icon" type="image/x-icon" href="/favicon.ico")
    %link(rel="apple-touch-icon" href="/icon.png")
    = csrf_meta_tags
    :javascript
      jQuery(document).ready(function($) {
        $('a[rel*=facebox]').facebox({
          loadingImage : '/assets/loading.gif',
          closeImage   : '/assets/closelabel.png'
        })
      })
  %body
    %header
      %h1
        = link_to root_path do
          %span.atnd ATND
          %span.groups GROUPING
      %p.usage
        %a{:href => "#usage", :rel => "facebox"} ?
    #body
      = yield
    #usage{:style => "display:none;"}
      %h1
        ATND GROUPING
      %p
        ATNDイベント参加者をランダムにグループ別けするツールです。
      %h2
        例えばこんなときに便利
      %ul
        %li いくつかのテーブルが用意されている会場での席決め。
        %li グループで行うハンズオンセミナーなどのグループ分け。
        %li 顔見知り同士が固まらない、一人ぼっちの人ができないなど、参加者への配慮。
      %h2
        使い方
      %ol
        %li 「URL」にATNDで立てたイベントのURLを貼りつけ。
        %li 「GROUPS」でグループ数を選択。
        %li シャッフルボタンをクリック。
        %li 表示されたグループ分けでよかったら「確定」をクリック。やり直す場合は「やり直す」をクリック。
        %li 「確定」をクリックして表示されたページの最下部にあるTweetボタンからそのページをTweetして参加者に告知。
      
  %footer
    %p.copyright
      created by
      %span= link_to '@func09', 'http://twitter.com/func09'
      , designed by 
      %span= link_to '@machida', 'http://twitter.com/machida'